//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SallaConnector.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SallaAccount
    {
        public string SallaMerchantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string SallaStoreName { get; set; }
        public bool IsActive { get; set; }
        public string SallaToken { get; set; }
        public string SallaRefreshToken { get; set; }
        public string EdaraTenantId { get; set; }
        public string EdaraTenantName { get; set; }
        public string EdaraEmail { get; set; }
        public string EdaraUser { get; set; }
        public string EdaraToken { get; set; }
        public Nullable<int> SallaInProgressStatusId { get; set; }
        public Nullable<int> SallaShippedStatusId { get; set; }
        public Nullable<int> EdaraCODServiceId { get; set; }
        public Nullable<int> EdaraShippingServiceId { get; set; }
        public Nullable<int> EdaraWarehouseId { get; set; }
        public Nullable<int> EdaraStoreId { get; set; }
        public Nullable<int> EdaraPriceListId { get; set; }
        public Nullable<bool> StockItemIncludeTax { get; set; }
        public Nullable<bool> ServiceItemIncludeTax { get; set; }
        public string PMCredit { get; set; }
        public string PMCOD { get; set; }
        public string PMMada { get; set; }
        public string PMApplePay { get; set; }
        public string PMTamara { get; set; }
        public string PMTaby { get; set; }
        public Nullable<int> TaxRateId { get; set; }
    }
}
